version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    command: >
      sh -c "npm run build && npm start"

  mosquitto:
    image: eclipse-mosquitto:2
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/conf.d:/mosquitto/config/conf.d
      - ./mosquitto/pwfile:/mosquitto/config/pwfile
      - mosquitto_data:/mosquitto/data
    ports:
      - "1883:1883"

  cart_consumer:
    build:
      context: .
      dockerfile: services/Dockerfile
    depends_on:
      - mosquitto
    env_file:
      - .env
    command: python cart_event_consumer.py

  cart_sync:
    build:
      context: .
      dockerfile: services/Dockerfile
    env_file:
      - .env
    command: python cart_sync_service.py

volumes:
  mosquitto_data:
