version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    command: >
      sh -c "npm run build && npm start"

  mosquitto:
    image: eclipse-mosquitto:2
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/conf.d:/mosquitto/config/conf.d
      - ./mosquitto/pwfile:/mosquitto/config/pwfile
      - mosquitto_data:/mosquitto/data
    ports:
      - "1883:1883"

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: cart
      POSTGRES_USER: cart
      POSTGRES_PASSWORD: cart
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  cart_consumer:
    build:
      context: .
      dockerfile: services/Dockerfile
    depends_on:
      - db
      - mosquitto
    env_file:
      - .env
    command: python cart_event_consumer.py

  cart_sync:
    build:
      context: .
      dockerfile: services/Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    command: python cart_sync_service.py

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  mosquitto_data:
  postgres_data:
  pgadmin_data:
