CREATE TABLE IF NOT EXISTS movement (
    id SERIAL PRIMARY KEY,
    inventory_id INTEGER,
    change INTEGER NOT NULL,
    reason TEXT,
    ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    staff_id INTEGER
);

CREATE SCHEMA IF NOT EXISTS drawer;
CREATE TABLE IF NOT EXISTS drawer.state (
    drawer_id INTEGER PRIMARY KEY,
    state TEXT NOT NULL,
    ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mqtt_outbox (
    id SERIAL PRIMARY KEY,
    topic TEXT NOT NULL,
    payload TEXT NOT NULL,
    sent BOOLEAN DEFAULT FALSE,
    ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
